### ISSUE TITLE
Can't found game room on game list (Use Linux and WarIII 1.28F)

### ISSUE THREAD

**Issue by Fatorin** [uakfdotb/ghostpp#33]
Hello, I want run ghostpp on linux, but I can't found game room on game list.

I complete the configuration and successfully connect to the server and I saw log and sure bot created room success.

I try to adjust firewall setting, but still can't see game room.

I used Ubuntu 16.04 and Warcraft III version is 1.28.5.

I used Windows can work, but I want run on linux.

Can you help me has happened and solution?

**Comment by maxemann96** [comment]
Can you leave some more information, such as log output, etc ...?

**Comment by uakfdotb** [comment]
Also make sure all the war3version config options are set to 28, especially lan_war3version

**Comment by Fatorin** [comment]
[ghost.log](https://github.com/uakfdotb/ghostpp/files/4448083/ghost.log)
[ghost.cfg.txt](https://github.com/uakfdotb/ghostpp/files/4448084/ghost.cfg.txt)
Thanks respond! I upload my config and log output , hope it helps.

**Comment by Fatorin** [comment]
I found this issue problem same with me.
I follow this step, now I can see room show on game list.
I'm sorry about that. Have same problem but I still post new issue.
https://github.com/uakfdotb/ghostpp/issues/31

**Comment by acollazo25** [comment]
Hi @Fatorin, you were able to complete your docker-based Pvpgn Pro & Ghost++ stack. I have used your repository, but I get this error in ghost when starting a game : `[UDPSOCKET] failed to broadcast packet (port 6112, size 105 bytes)`
Could you give me some help, do you have a working docker-compose?
Thanks.

**Comment by Fatorin** [comment]
> Hi @Fatorin, you were able to complete your docker-based Pvpgn Pro & Ghost++ stack. I have used your repository, but I get this error in ghost when starting a game : `[UDPSOCKET] failed to broadcast packet (port 6112, size 105 bytes)`
> Could you give me some help, do you have a working docker-compose?
> Thanks.

I only use Ghost++ by docker-compose.
You can check on my Github [Here](https://github.com/Fatorin/ghostpp_docker/blob/main/config/docker-compose.yml)

And Pvpgn Pro docker version I was follow [here](https://hub.docker.com/r/wwmoraes/pvpgn-server#usage).
Pvpgn pro docker I not use docker-compose, just use command build.
I think your firewall or port setting has problem.
Make sure pvpgn and ghost++ port can't same.

**Comment by acollazo25** [comment]
> You can check on my Github Here
> And Pvpgn Pro docker version I was follow here.

Yes, I use exactly those same repositories. 
The error described above happens when I disable the `udp_dontroute = 1` routing, trying to solve another problem listed in the **bnetd.log** -> ` handle_udp_packet: [22] got unknown udp packet type 0x8730f7, len 135 from 192.168.0.3: 36408`.

> Make sure pvpgn and ghost++ port can't same.

I use a configuration similar to your repository for `ghost.cfg` using ports *6113*, *6114*, *6115*

Below is my *docker-compose.yaml*, my ghost client is able to connect and join the **Warcraft 3 Frozen Throne** channel, the error starts when creating a new game.
`handle_udp_packet: [22] got unknown udp packet type 0x8730f7, len 135 from 192.168.0.3: 36408`

Something is missing and I have not been able to realize it, thank you.

```yaml
version: "3.7"

services:
  pvpgn:
    restart: unless-stopped
    container_name: pvpgn_server
    image: wwmoraes/pvpgn-server
    user: pvpgn
    volumes:
      - ./pvpgn/etc:/usr/local/pvpgn/etc
      - ./pvpgn/var:/usr/local/pvpgn/var
    ports:
      - 4000:4000
      - 6112:6112
      - 6200:6200

  ghostpp:
    restart: unless-stopped
    container_name: ghostpp_server
    image: fatorin/ghostpp:1.3
    ports:
      - 6113:6113
      - 6114:6114
      - 6115:6115
    volumes:
      - ./ghostpp/config:/app/config
      - ./ghostpp/maps:/app/maps
    command: ./ghost++ "./config/ghost.cfg"
```
